import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import ApolloContext from './lib/ApolloContext'
import Theme from './theme'

export const metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloContext>
          <Theme>
            {children}
          </Theme>
        </ApolloContext>
      </body>
    </html>
  )
}
