import './globals.css'
import { Inter } from 'next/font/google'
import ApolloContext from './lib/ApolloContext'
import Theme from './theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloContext>
          <Theme>
            {children}
          </Theme>
        </ApolloContext>
      </body>
    </html>
  )
}
